/* Semsar Talabak — Cloudflare Worker V24
 * Public contract: POST JSON { message, history, qualificationScore, canShareWhatsapp, formState }
 * Required secrets: GEMINI_API_KEY. Optional vars: AI_FEED_URL, REQUESTS_KV.
 */

const GEMINI_MODEL = 'gemini-3.5-flash-lite';
const DEFAULT_FEED_URL = 'https://nasr-realestate.github.io/ai-feed.json';
const ALAA_PHONE = '+201022171667';
const OFFICE_ADDRESS = '16 شارع محمد حسن الجمل - المنطقة السادسة - مدينة نصر';
const OFFICE_MAP_URL = 'https://maps.app.goo.gl/jQBJvzA4vzo6Qe7';
const OFFICE_HOURS = 'من 12 الضهر لحد 9 بالليل، ما عدا الجمعة';
const MIN_SCORE_THRESHOLD = 25;
const CACHE_TTL_MS = 5 * 60 * 1000;
const MAIN_MENU_BUTTONS = ['🔍 أشتري', '🏠 أستأجر', '💰 أبيع', '🔑 أأجر'];
const POST_COMPLETE_BUTTONS = ['✅ ابعت على واتساب', '⬅️ عدّل حاجة', '🆕 طلب جديد'];
const OUTSIDE_AREAS = ['التجمع', 'مصر الجديدة', 'هليوبوليس', 'فيصل', 'الهرم', 'أكتوبر', 'المعادي', 'الشيخ زايد', 'الشروق', 'بدر', 'حدائق الأهرام', 'شبرا', 'المهندسين', 'الزمالك', 'العاصمة', 'مدينتي', 'الرحاب', 'المقطم', 'حلوان', 'وسط البلد', 'السيدة زينب', 'المرج', 'عين شمس', 'المطرية', 'الزيتون', 'العباسية', 'التحرير', 'المنيل', 'مصر القديمة'];
const NASR_CITY_TERMS = ['مدينة نصر', 'المنطقة السادسة', 'المنطقة السابعة', 'المنطقة الثامنة', 'المنطقة التاسعة', 'المنطقة العاشرة', 'المنطقة الحادية عشر', 'المنطقة الحادية عشرة', 'الحي الأول', 'الحي الثاني', 'الحي السابع', 'الحي العاشر', 'مكرم عبيد', 'عباس العقاد', 'حسن المأمون', 'مصطفى النحاس', 'المقريفي', 'محمد المقريف', 'النزهة', 'الطيران', 'السفارات', 'حديقة الطفل', 'الرقابة الإدارية', 'شارع النصر', 'نادي المقاولين'];
const MENU_TEXT = 'اختار محتاج إيه:';
const cache = { feed: null, expires: 0 };
const rate = new Map();

function json(data, status = 200) {
  return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Content-Type', 'access-control-allow-methods': 'POST, OPTIONS' } });
}
function normalizeAr(value = '') { return String(value).toLowerCase().replace(/[إأآ]/g, 'ا').replace(/ى/g, 'ي').replace(/[ًٌٍَُِّْـ]/g, '').replace(/[،,؛;]/g, ' ').replace(/\s+/g, ' ').trim(); }
function hasAny(text, terms) { const n = normalizeAr(text); return terms.some(t => n.includes(normalizeAr(t))); }
function isInNasrCity(text) { return hasAny(text, NASR_CITY_TERMS); }
function isOutOfCoverage(text) { return hasAny(text, OUTSIDE_AREAS); }
function parseNumeric(value) { const s = String(value || '').replace(/[٠-٩]/g, d => '٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[,٬]/g, '').replace(/مليون/g, '000000').replace(/الف|ألف/g, '000'); const m = s.match(/\d+(?:\.\d+)?/); return m ? Number(m[0]) : 0; }
function extractFullPrice(value) { const n = normalizeAr(value).replace(/,/g, ''); const m = n.match(/(\d+(?:\.\d+)?)\s*(مليون|الف|الف جنيه|جنيه)?/); if (!m) return 0; const x = Number(m[1]); return m[2] && m[2].includes('مليون') ? x * 1000000 : m[2] ? x * 1000 : x; }
function phone(value) { const digits = String(value || '').replace(/\D/g, ''); return /^(01)[0-2,5]\d{8}$/.test(digits) ? digits : ''; }
function option(value, values) { const n = normalizeAr(value); return values.find(v => n === normalizeAr(v) || n.includes(normalizeAr(v))) || ''; }
function menu(extra = {}) { return { ...extra, options: MAIN_MENU_BUTTONS }; }
function outsideResponse() { return menu({ response: 'معلش، شغلي في مدينة نصر بس. لو طلبك في منطقة تانية مش هقدر أسجّله هنا.', reply: 'معلش، شغلي في مدينة نصر بس. لو طلبك في منطقة تانية مش هقدر أسجّله هنا.' }); }
function progress(state, total) { const current = Math.min((state?.stepIndex ?? -1) + 1, total); return { current, total, remaining: Math.max(total - current, 0), percent: Math.round(((current - 1) / total) * 100) }; }
function baseState(flowType, type) { return { active: true, flowType, type, stepIndex: 0, data: {}, awaitingQuestion: false }; }
function response(text, state, opts, extras = {}) { const total = state?.flowType === 'buyer' ? 6 : 11; return { response: text, reply: text, options: opts, formState: state, progress: progress(state, total), ...extras }; }
function flowButtons(opts) { return [...opts, '⬅️ رجوع']; }
function ownerButtons(opts) { return [...opts, '⬅️ رجوع', 'تخطي السؤال ⏭', 'ابعت البيانات دلوقتي ✅', 'إلغاء التسجيل ✕']; }
function ownerQuestions(type, step, data) {
  const sale = type === 'sale';
  if (sale) return [
    ['نوع العقار؟', ['شقة', 'مكتب إداري', 'محل تجاري']], ['العقار فين في مدينة نصر؟ (الشارع - المنطقة)', []], ['المساحة كام متر؟', []], ['طالب فيه كام؟', []], ['عدد الغرف؟', ['2', '3', '4', '5+']], ['عدد الحمامات؟', ['1', '2', '3+']], ['الدور؟', ['أرضي', 'أول', 'ثاني', 'متكرر', 'أخير']], ['التشطيب؟', ['كامل التشطيب', 'لوكس', 'سوبر لوكس', 'نص تشطيب', 'على الطوب']], ['اسمك إيه؟', []], ['رقمك كام؟ (11 رقم يبدأ بـ01)', []], ['فيه أي ملاحظات أو تفاصيل مهمة؟', []]
  ][step];
  return [
    ['نوع العقار؟', ['شقة', 'مكتب إداري', 'محل تجاري']], ['العقار فين في مدينة نصر؟ (الشارع - المنطقة)', []], ['المساحة كام متر؟', []], ['العقار مفروش ولا فاضي؟', ['مفروش', 'فاضي']], ['مدة الإيجار؟', ['أسبوعي', 'شهري', 'سنوي']], ['السعر كام؟', []], ['حالة الفرش؟', ['فاخر', 'جيد جداً', 'متوسط']], ['المدة المطلوبة؟', ['شهر', '3 شهور', '6 شهور', 'سنة']], ['السعر كام؟', []], ['عدد الغرف؟', ['2', '3', '4', '5+']], ['عدد الحمامات؟', ['1', '2', '3+']], ['الدور؟', ['أرضي', 'أول', 'ثاني', 'متكرر', 'أخير']], ['التشطيب؟', ['كامل التشطيب', 'لوكس', 'سوبر لوكس', 'نص تشطيب', 'على الطوب']], ['اسمك إيه؟', []], ['رقمك كام؟ (11 رقم يبدأ بـ01)', []], ['فيه أي ملاحظات أو تفاصيل مهمة؟', []]
  ][step];
}
function ownerTotal(type, data = {}) { return type === 'sale' ? 11 : (data.furnished === 'مفروش' ? 16 : 14); }
function buyerQuestion(state) { const rent = state.type === 'rent'; return [
  ['نوع العقار؟', rent ? ['شقة', 'مكتب إداري', 'محل تجاري'] : ['شقة', 'مكتب إداري', 'محل تجاري', 'فيلا']],
  ['المنطقة في مدينة نصر؟', ['المنطقة السادسة', 'المنطقة السابعة', 'المنطقة الثامنة', 'المنطقة التاسعة', 'المنطقة العاشرة', 'عباس العقاد', 'مصطفى النحاس', 'الحي السابع', 'مكرم عبيد', 'أي منطقة في مدينة نصر']],
  ['الميزانية كام؟', []], ['عدد الغرف؟', ['2', '3', '4', '5+']], ['هتشتري امتى؟', ['بأسرع وقت', 'خلال شهر', 'خلال 3 شهور', 'بستكشف']], ['رقمك كام؟ (11 رقم يبدأ بـ01)', []]
][state.stepIndex]; }
function detectIntent(text) { const n = normalizeAr(text); if (n.includes('اشتري') || n.includes('شراء')) return 'BUY'; if (n.includes('استاجر') || n.includes('ايجار') || n.includes('إيجار')) return 'RENT'; if (n.includes('ابيع') || n.includes('بيع')) return 'SELL_OWN'; if (n.includes('اجر') || n.includes('تاجير') || n.includes('تأجير')) return 'RENT_OWN'; if (n.includes('معلومة') || n.includes('عنوان') || n.includes('مواعيد')) return 'INFO'; return ''; }
function newFlow(intent) { if (intent === 'BUY') return baseState('buyer', 'sale'); if (intent === 'RENT') return baseState('buyer', 'rent'); if (intent === 'SELL_OWN') return baseState('owner', 'sale'); if (intent === 'RENT_OWN') return baseState('owner', 'rent'); return null; }
function buildLead(state) { const d = state.data || {}; return { type: state.flowType === 'buyer' ? (state.type === 'rent' ? 'استئجار' : 'شراء') : (state.type === 'rent' ? 'تأجير عقار' : 'بيع عقار'), price: d.budget || d.price || 'حسب الاتفاق', name: d.ownerName || '', phone: d.ownerPhone || d.phone || '' }; }
function buildWa(state) { const d = state.data || {}; return `السلام عليكم أ. طارق،\nأنا ${state.flowType === 'owner' ? 'المالك' : 'العميل'}: ${d.ownerName || ''}\nعايز ${state.type === 'rent' ? 'إيجار' : 'بيع/شراء'} عقار في مدينة نصر.\n─────────────────\n${Object.entries(d).map(([k, v]) => `• ${k}: ${v}`).join('\n')}\n─────────────────\n📱 رقم التواصل: ${d.ownerPhone || d.phone || ''}`; }
function ownerKey(type, step, data = {}) { if (type === 'sale') return ['propertyType', 'location', 'area', 'price', 'rooms', 'baths', 'floor', 'finishing', 'ownerName', 'ownerPhone', 'notes'][step]; if (step <= 3) return ['propertyType', 'location', 'area', 'furnished'][step]; if (data.furnished === 'مفروش') return ['rentPeriod', 'price', 'furnitureQuality', 'rooms', 'baths', 'floor', 'finishing', 'ownerName', 'ownerPhone', 'notes'][step - 4]; return ['duration', 'price', 'rooms', 'baths', 'floor', 'finishing', 'ownerName', 'ownerPhone', 'notes'][step - 4]; }
async function feed(env) { const now = Date.now(); if (cache.feed && cache.expires > now) return cache.feed; const r = await fetch(env.AI_FEED_URL || DEFAULT_FEED_URL, { cf: { cacheTtl: 300 } }); const j = await r.json(); cache.feed = j.properties || []; cache.expires = now + CACHE_TTL_MS; return cache.feed; }
function filterProperties(items, d) { const budget = extractFullPrice(d.budget || d.price); return items.filter(p => { const loc = `${p.location || ''} ${p.title || ''}`; if (!isInNasrCity(loc) || isOutOfCoverage(loc)) return false; if (d.type && p.transaction && p.transaction !== d.type) return false; if (d.propertyType && p.propertyType && p.propertyType !== d.propertyType) return false; const pp = extractFullPrice(p.priceNumeric || p.price); if (budget && pp) { const tolerance = d.type === 'rent' ? .4 : .25; if (Math.abs(pp - budget) / budget > tolerance) return false; } return true; }); }
async function buyerComplete(state, env) { const items = await feed(env); const hits = filterProperties(items, state.data); const d = state.data; if (!hits.length) { const text = `مفيش ${d.propertyType || 'عقار'} في ${d.landmark || 'مدينة نصر'} بميزانية ${d.budget || 'المحددة'} ج.م حالياً.\n\nبس أقدر أسجّل طلبك كامل وأبعته لطارق يدورلك عند الزملاء والمكاتب المعتمدة في نفس المنطقة.\n\nعايز أسجّل؟`; state.flowType = 'buyer_no_results'; state.active = true; state.stepIndex = -1; return response(text, state, ['✅ أيوه سجّل طلبي', '❌ لا شكراً'], { leadData: buildLead(state) }); } const names = hits.slice(0, 3).map((p, i) => `${i + 1}. ${p.title || 'عقار مناسب'}\n${p.location || ''}\n${p.price || ''}`).join('\n\n'); state.active = false; return menu({ response: `لقيتلك ${hits.length} اختيارات مناسبة:\n\n${names}\n\nلو عايز أسجّل طلب أدق أو تتكلم مع طارق، اختار من القائمة.`, reply: `لقيتلك ${hits.length} اختيارات مناسبة:\n\n${names}`, formState: state, leadData: buildLead(state), options: MAIN_MENU_BUTTONS }); }
async function geminiBrief(message, history, env) { if (!env.GEMINI_API_KEY) return ''; const body = { contents: [{ role: 'user', parts: [{ text: JSON.stringify({ message, history: (history || []).slice(-6) }) }] }], systemInstruction: { parts: [{ text: 'أنت مساعد عقاري مصري لمكتب متخصص في مدينة نصر فقط. أجب بالعربية المصرية المباشرة باختصار، بدون ترحيب أو ادعاء أنك ذكاء اصطناعي، ولا تقترح مناطق خارج مدينة نصر. أعد JSON بالشكل {"answer":"..."}.' }] }, generationConfig: { temperature: 0.1, maxOutputTokens: 120, responseMimeType: 'application/json' } }; const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${env.GEMINI_API_KEY}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); if (!r.ok) return ''; try { const j = await r.json(); return JSON.parse(j.candidates?.[0]?.content?.parts?.[0]?.text || '{}').answer || ''; } catch { return ''; } }
async function analyzeIntent(message, history, env) { const canned = detectIntent(message); if (canned) return canned; return ''; }
function applyOwnerValue(state, value) { const step = state.stepIndex; const d = state.data; const type = state.type; if (value === 'إلغاء التسجيل ✕') { state.active = false; return state; } if (value === '⬅️ رجوع') { state.stepIndex = Math.max(0, step - 1); return state; } if (value === 'تخطي السؤال ⏭') { state.stepIndex++; return state; } const q = ownerQuestions(type, step, d); if (!q) return state; const key = ownerKey(type, step, d); if (key === 'ownerPhone') { const p = phone(value); if (!p) return state; d[key] = p; } else if (key === 'location') { if (isOutOfCoverage(value) || !isInNasrCity(value)) { state.flowType = 'out_of_coverage'; state.active = false; return state; } d[key] = value; } else if (key === 'price') { d[key] = String(extractFullPrice(value) || value); } else if (key === 'propertyType' || key === 'furnished' || key === 'rentPeriod' || key === 'duration') { d[key] = option(value, q[1]) || value; } else if (key === 'rooms' || key === 'baths') { d[key] = parseNumeric(value) || value; } else d[key] = value; state.stepIndex++; return state; }
async function processOwner(message, state, env) { if (state.stepIndex === -1) return menu({ response: 'تم إلغاء التسجيل. اختار طلبك لما تحتاج.', reply: 'تم إلغاء التسجيل. اختار طلبك لما تحتاج.', formState: { active: false } }); const before = state.stepIndex; const next = applyOwnerValue(state, message); if (next.flowType === 'out_of_coverage') return outsideResponse(); if (!next.active) return menu({ response: 'تمام، وقفت التسجيل. اختار طلبك لما تحتاج.', reply: 'تمام، وقفت التسجيل. اختار طلبك لما تحتاج.', formState: { active: false } }); if (next.stepIndex >= ownerTotal(next.type, next.data)) { next.active = false; return menu({ response: 'تمام، البيانات جاهزة ✅', reply: 'تمام، البيانات جاهزة ✅', formState: next, options: POST_COMPLETE_BUTTONS, leadData: buildLead(next), waMessage: buildWa(next), readyToSend: true }); } const q = ownerQuestions(next.type, next.stepIndex, next.data); if (!q) return menu({ response: 'تمام، البيانات جاهزة ✅', reply: 'تمام، البيانات جاهزة ✅', formState: next, options: POST_COMPLETE_BUTTONS, leadData: buildLead(next), waMessage: buildWa(next), readyToSend: true }); const text = before === next.stepIndex && !['⬅️ رجوع', 'تخطي السؤال ⏭'].includes(message) ? `اختار من الأزرار.\n\n${q[0]}` : `${q[0]}\n\n(${next.stepIndex + 1}/${ownerTotal(next.type, next.data)})`; return response(text, next, ownerButtons(q[1])); }
async function processBuyer(message, state, env) { if (message === '⬅️ رجوع') { state.stepIndex = Math.max(0, state.stepIndex - 1); } else { const q = buyerQuestion(state); const d = state.data; const step = state.stepIndex; if (step === 0) { d.propertyType = option(message, q[1]); if (!d.propertyType) return response(`اختار نوع العقار من الأزرار.\n\n${q[0]}`, state, flowButtons(q[1])); } else if (step === 1) { if (isOutOfCoverage(message) || (!isInNasrCity(message) && normalizeAr(message) !== normalizeAr('أي منطقة في مدينة نصر'))) return outsideResponse(); d.landmark = message; } else if (step === 2) { d.budget = String(extractFullPrice(message) || message); } else if (step === 3) { d.rooms = parseNumeric(message) || message; } else if (step === 4) { d.urgency = message; } else if (step === 5) { const p = phone(message); if (!p) return response('اكتب رقم موبايل صحيح 11 رقم ويبدأ بـ01.', state, ['⬅️ رجوع']); d.phone = p; return buyerComplete(state, env); } state.stepIndex++; } const q = buyerQuestion(state); return response(`${q[0]}\n\n(${state.stepIndex + 1}/6)`, state, flowButtons(q[1])); }
async function handle(message, body, env) { const state = body.formState; if (state?.active && state.flowType === 'buyer_no_results') { if (hasAny(message, ['ايوه', 'سجل', 'نعم'])) { state.active = false; return menu({ response: 'تمام، سجلت طلبك ✅\nهبعت طلبك لطارق يدورلك عند الزملاء والمكاتب المعتمدة.', reply: 'تمام، سجلت طلبك ✅\nهبعت طلبك لطارق يدورلك عند الزملاء والمكاتب المعتمدة.', formState: state, flowType: 'buyer_completed', leadData: buildLead(state), options: POST_COMPLETE_BUTTONS }); } state.active = false; return menu({ response: 'تمام، مش هسجّل الطلب. اختار طلبك لما تحتاج.', reply: 'تمام، مش هسجّل الطلب. اختار طلبك لما تحتاج.', formState: state }); } if (state?.active && state.flowType === 'buyer') return processBuyer(message, state, env); if (state?.active && state.flowType === 'owner') return processOwner(message, state, env); if (isOutOfCoverage(message) && !isInNasrCity(message)) return outsideResponse(); const intent = await analyzeIntent(message, body.history, env); const next = newFlow(intent); if (next) { const q = next.flowType === 'buyer' ? buyerQuestion(next) : ownerQuestions(next.type, 0, {}); return response(`${q[0]}\n\n(1/${next.flowType === 'buyer' ? 6 : 11})`, next, next.flowType === 'buyer' ? flowButtons(q[1]) : ownerButtons(q[1]), { leadData: { type: next.flowType === 'buyer' ? 'شراء (جاري)' : 'طلب مالك (جاري)' } }); } if (intent === 'INFO') return menu({ response: `العنوان: ${OFFICE_ADDRESS}\nالمواعيد: ${OFFICE_HOURS}\nالخريطة: ${OFFICE_MAP_URL}\nللتواصل: ${ALAA_PHONE}`, reply: `العنوان: ${OFFICE_ADDRESS}\nالمواعيد: ${OFFICE_HOURS}\nالخريطة: ${OFFICE_MAP_URL}\nللتواصل: ${ALAA_PHONE}` }); const answer = await geminiBrief(message, body.history, env); return menu({ response: answer || MENU_TEXT, reply: answer || MENU_TEXT }); }

export default { async fetch(request, env) { if (request.method === 'OPTIONS') return json({ ok: true }); if (request.method !== 'POST') return json({ error: 'Method not allowed' }, 405); const ip = request.headers.get('CF-Connecting-IP') || 'unknown'; const now = Date.now(); const hits = (rate.get(ip) || []).filter(t => now - t < 30000); if (hits.length >= 15) return json({ response: 'استنى شوية وحاول تاني.', reply: 'استنى شوية وحاول تاني.', options: MAIN_MENU_BUTTONS }, 429); hits.push(now); rate.set(ip, hits); try { const body = await request.json(); const message = String(body.message || '').trim(); if (!message) return json(menu({ response: MENU_TEXT, reply: MENU_TEXT })); return json(await handle(message, body, env)); } catch (e) { return json(menu({ response: 'حصل عطل مؤقت. جرّب تاني بعد شوية.', reply: 'حصل عطل مؤقت. جرّب تاني بعد شوية.' }), 200); } } };

export { isOutOfCoverage, isInNasrCity, parseNumeric, extractFullPrice, detectIntent, MAIN_MENU_BUTTONS };
