name = "noisy-bush-fd84"
main = "valuation-worker.js"
compatibility_date = "2026-09-29"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "nasr-market-db"
database_id = "ace5c9a2-c6b1-47b3-adf1-77e84ac50abf"
